import pyautogui
import keyboard
import pydirectinput
import time
import psutil

resetCount = 0

def usingWhileTrue():
    while True:
        print(f'Uso da CPU: {psutil.cpu_percent()}%')
        time.sleep(3)
        pyautogui.click(154, 222)
        pydirectinput.keyDown('space')
        time.sleep(1)
        pydirectinput.keyUp('space')
        pydirectinput.keyDown('space')
        time.sleep(1)
        pydirectinput.keyUp('space')
        time.sleep(0.8)
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        time.sleep(0.8)
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        time.sleep(0.8)
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        time.sleep(2)
        print('entra aq')
        pydirectinput.keyDown('right')
        time.sleep(1)
        pydirectinput.keyUp('right')

        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        time.sleep(0.8)
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        pydirectinput.keyDown('x')
        time.sleep(1)
        pydirectinput.keyUp('x')
        time.sleep(4)
        normalColor = pyautogui.pixelMatchesColor(87, 216, (199, 109, 44))
        if normalColor:
            print("deu certo")
            resetCount += 1
            print(resetCount)
            pydirectinput.keyDown('l')
            pydirectinput.keyDown('r')
            pydirectinput.keyDown('space')
            pydirectinput.keyDown('tab')
            time.sleep(1)
            pydirectinput.keyUp('l')
            pydirectinput.keyUp('r')
            pydirectinput.keyUp('space')
            pydirectinput.keyUp('tab')
        else:
            print("shiny")
            keyboard.wait('h')


def usingRecursion(resetCounter):
    print(f'Uso da CPU: {psutil.cpu_percent()} - recursao %')
    time.sleep(7)
    print('ta dando o space inicial')
    pydirectinput.PAUSE = 0.1
    #intro
    pydirectinput.press('space')
    time.sleep(1)
    print('ta dando o segundo space')

    pydirectinput.press('space')
    time.sleep(2)
    print('ta clicando o x pra selecionar o jogo')

    #continue game
    pydirectinput.press('x')
    
    #open mala
    time.sleep(2)
    print('ta apertando x pra abrir mala')

    pydirectinput.press('x')

    time.sleep(4)
    # dialogo these are pokeballs
    print('eh pra estar no dialogo these are pokeballs')
    pydirectinput.press('x')
    time.sleep(3)

    print('agora ta clicando direita')
    pydirectinput.press('right')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    # 8x
    print('começa dialogos')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')

    print('Professor vai embora')
    time.sleep(2)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')

    print('aluno vai embora')
    time.sleep(2)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')
    time.sleep(1)
    pydirectinput.press('x')

    print('pausa do amarelo')
    time.sleep(3)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')
    time.sleep(0.5)
    pydirectinput.press('x')

    print('fim dos x e inicio da batalha')

    # print('inciiando batalha')
    # time.sleep(0.5)
    # pydirectinput.press('x')
    # time.sleep(0.5)
    # pydirectinput.press('x')
    # time.sleep(0.5)
    # pydirectinput.press('x')
    # time.sleep(0.5)
    # pydirectinput.press('x')
    # pydirectinput.keyUp('space')
    # pyautogui.click(154, 222)
    
    # pydirectinput.keyDown('space')
    # time.sleep(1)
    # pydirectinput.keyUp('space')
    # time.sleep(0.8)
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # time.sleep(0.8)
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # time.sleep(0.8)
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # time.sleep(2)
    # print('entra aq')
    # pydirectinput.keyDown('right')
    # time.sleep(1)
    # pydirectinput.keyUp('right')

    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # time.sleep(0.8)
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    # pydirectinput.keyDown('x')
    # time.sleep(1)
    # pydirectinput.keyUp('x')
    time.sleep(5)
    print('checa cor')
    normalColor = pyautogui.pixelMatchesColor(87, 216, (199, 109, 44))
    if normalColor:
        print("deu certo")
        resetCounter += 1
        print(resetCounter)
        pydirectinput.keyDown('l')
        pydirectinput.keyDown('r')
        pydirectinput.keyDown('space')
        pydirectinput.keyDown('tab')
        time.sleep(1)
        pydirectinput.keyUp('l')
        pydirectinput.keyUp('r')
        pydirectinput.keyUp('space')
        pydirectinput.keyUp('tab')
        usingRecursion(resetCounter)
    else:
        print("shiny")
        keyboard.wait('h')

usingRecursion(0)